version: '3.9'

services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: gui
      POSTGRES_PASSWORD: gui_pwd
      POSTGRES_DB: rota_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U gui -d rota_db']
      interval: 5s
      retries: 5

  api:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg://gui:gui_pwd@db:5432/rota_db
      ADMIN_PASSWORD: super-secreta
      ORS_API_KEY: 5b3ce3597851110001cf6248dd952248d5e3474e87d768da5b5aff3d
    ports:
      - '5000:5000'

volumes:
  pgdata:
